[package]
name = "antisequence"
version = "0.1.0"
edition = "2021"

[dependencies]
needletail = "0.5"
rustc-hash = "1.1"
flate2 = { version = "1.0", features = ["zlib-ng"], default-features = false }
regex = "1.8"
thiserror = "1.0"
rand = { version = "0.8", default-features = false }
rand_xoshiro = "0.6"
thread_local = "1.1"
memchr = "2.5"
colored = "2.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
cfg-if = "1.0"
rayon = "1.10"
smallvec = "1.11"
parking_lot = "0.12"
# optional global allocators
mimalloc = { version = "0.1", optional = true }
jemallocator = { version = "0.5", optional = true }

[features]
default = []
# Enable Microsoft mimalloc as global allocator
mimalloc = ["dep:mimalloc"]
# Enable jemalloc as global allocator
jemalloc = ["dep:jemallocator"]

[target.'cfg(target_arch = "x86_64")'.dependencies]
block-aligner = { version = "0.5", features = ["simd_avx2"] }
[target.'cfg(target_arch = "aarch64")'.dependencies]
block-aligner = { version = "0.5", features = ["simd_neon"] }

[profile.bench]
opt-level = 3
codegen-units = 1
lto = "thin"
debug = false
debug-assertions = false
overflow-checks = false
strip = false
